name: Releases lib

on:
  workflow_dispatch:

jobs:
  releases-core:
    runs-on: ubuntu-latest
    container: node:24
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: npm install --global bun
      - run: bun install --frozen-lockfile
      - run: bun run build
      - run: |
          cd dist
          npm publish --access public
